config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :auth do
    post 'cpplogin', to: 'authentication#login'
    post 'logout', to: 'authentication#logout'
    get 'callback', to: 'authentication#callback'
  end

  namespace :recruit do
    get 'mailing/add', to: 'recruiting_mailing#new'
    post 'mailing/add', to: 'recruiting_mailing#create'
  end

  resources :reimbursements do
    post :accept
    post :reject
  end

  resources :users do
    collection do
      get 'profile'
      get 'welcome_application'

      resources :mails
    end
  end

  resources :applications, as: :application do
    post :accept
    post :reject
  end
end

app/models/application.rb
class Application < ApplicationRecord
  include AASM

  default_scope { order(created_at: :desc) }

  validates :character_id, presence: true
  validates :token, presence: true
  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  aasm column: 'status' do
    state :pending, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: [:pending], to: :accepted
    end

    event :reject do
      transitions from: [:pending], to: :rejected
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Auth::SessionsHelper
  include Pundit

  before_action :touch_session

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def touch_session
    current_user
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    authorize Application
    @applications = Application.where(status: 'pending').all
  end

  def show
    application = Application.find(params[:id])
    authorize application

    @user = application
    @user_service = UserService.new(application.token)
  end

  def accept
    application_service = ApplicationService.new(params[:application_id])
    authorize application_service.application

    application_service.accept!

    flash[:success] = 'Application accepted'
    redirect_to application_index_path
  end

  def reject
    application_service = ApplicationService.new(params[:application_id])
    authorize application_service.application

    application_service.reject!

    flash[:success] = 'Application rejected'
    redirect_to application_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def portrait_url(type, id, size)
    case type.to_sym
    when :character
      "https://imageserver.eveonline.com/Character/#{id}_#{size}.jpg"
    when :corporation
      "https://imageserver.eveonline.com/Corporation/#{id}_#{size}.png"
    when :alliance
      "https://imageserver.eveonline.com/Alliance/#{id}_#{size}.png"
    end
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_suspicious_items.html.erb
<div id="user-suspicious-items" class="hidden">
  <% if user_service.character_suspicious_items.empty? %>
    <h3> No suspicious items detected</h3>
  <% else %>
    <table class="table fuschia_table">
      <thead class="thead-dark">
      <tr>
        <th width="5%" scope="col">#</th>
        <th class="text-left" width="75%" scope="col">Name</th>
        <th width="20%" scope="col">Quantity</th>
      </tr>
      </thead>
      <tbody>
        <% user_service.character_suspicious_items.each_with_index do |asset, index| %>
          <tr>
            <td>
              <%= index + 1 %>
            </td>
            <td class="text-left">
              <%= asset[:name] %>
            </td>
            <td class="text-left">
              <%= asset[:quantity] %>
            </td>
          </tr>
        <% end  %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/applications/index.html.erb
<div class="row">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th width="10%" scope="col">Date</th>
      <th width="55%" scope="col">Name</th>
      <th width="30%" scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @applications.each_with_index do |application, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td>
          <%= application.created_at.to_date %>
        </td>
        <td>
          <img width="32" height="32" src="<%= portrait_url(:character, application.character_id, 32) %>">
          <%= application.name %>
        </td>
        <td>
          <%= link_to 'View', application_path(application), class: 'btn btn-primary' %>
          |||
          <%= link_to application_accept_path(application), method: :post do %>
            <span class="btn btn-success">Accept</span>
          <% end %>
          <%= link_to application_reject_path(application), method: :post do %>
            <span class="btn btn-danger">Reject</span>
          <% end %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/applications/show.html.erb
<div id="profile-nabvar" class="container navbar navbar-inverse navbar-fixed-left profile-nabvar">
  <ul class="nav navbar-nav">
    <li><a href="#user-general">General</a></li>
    <li><a href="#user-finances">Finance</a></li>
    <li><a href="#user-employment">Employment</a></li>
    <li><a href="#user-contacts">Contacts</a></li>
    <li><a href="#user-mails">Mails</a></li>
  </ul>
</div>

<div id="user-profile" class="user-profile-container panel-container container">
  <%= render '/user/general_info', user: @user, user_service: @user_service %>
  <%= render '/user/finances_info', user_service: @user_service %>
  <%= render '/user/employment_info', user_service: @user_service %>
  <%= render '/user/contacts_info', user_service: @user_service %>
  <%= render '/user/mails_info', user_service: @user_service %>
</div>