config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :auth do
    post 'cpplogin', to: 'authentication#login'
    post 'logout', to: 'authentication#logout'
    get 'callback', to: 'authentication#callback'
  end

  namespace :recruit do
    get 'mailing/add', to: 'recruiting_mailing#new'
    post 'mailing/add', to: 'recruiting_mailing#create'
  end

  resources :reimbursements do
    post :accept
    post :reject
  end

  resources :users do
    collection do
      get 'profile'
      get 'welcome_application'

      resources :mails
    end
  end

  resources :applications, as: :application do
    post :accept
    post :reject
  end
end

app/models/application.rb
class Application < ApplicationRecord
  include AASM

  default_scope { order(created_at: :desc) }

  validates :character_id, presence: true
  validates :token, presence: true
  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  aasm column: 'status' do
    state :pending, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: [:pending], to: :accepted
    end

    event :reject do
      transitions from: [:pending], to: :rejected
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
end

app/models/eve_mail.rb
class EveMail
end

app/models/recruiting_mailing.rb
class RecruitingMailing < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/reimbursement.rb
class Reimbursement < ApplicationRecord
  include AASM

  belongs_to :user

  default_scope { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :zkb_link, presence: true, uniqueness: true
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  aasm column: 'status' do
    state :pending, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: [:pending, :accepted,:rejected], to: :accepted
    end

    event :reject do
      transitions from: [:pending, :accepted,:rejected], to: :rejected
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  include AccountSetup

  has_many :roles, dependent: :destroy
  has_many :reimbursements, dependent: :destroy

  validates :user_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :character_id, presence: true, uniqueness: true
  validates :corporation_id, presence: true
  validates :alliance_id, presence: true
  validates :token, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Auth::SessionsHelper
  include Pundit

  before_action :touch_session

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def touch_session
    current_user
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    authorize Application
    @applications = Application.where(status: 'pending').all
  end

  def show
    application = Application.find(params[:id])
    authorize application

    @user = application
    @user_service = UserService.new(application.token)
  end

  def accept
    application_service = ApplicationService.new(params[:application_id])
    authorize application_service.application

    application_service.accept!

    flash[:success] = 'Application accepted'
    redirect_to application_index_path
  end

  def reject
    application_service = ApplicationService.new(params[:application_id])
    authorize application_service.application

    application_service.reject!

    flash[:success] = 'Application rejected'
    redirect_to application_index_path
  end
end

app/controllers/mail_controller.rb
class MailController < ApplicationController
  def show
    authorize EveMail

    @mail = UserService.new(current_user.token).character_mail(params[:id])
  end
end

app/controllers/mails_controller.rb
class MailsController < ApplicationController
  def show
    authorize EveMail

    @mail = UserService.new(current_user.token).character_mail(params[:id])
  end
end

app/controllers/reimbursements_controller.rb
class ReimbursementsController < ApplicationController
  def index
    authorize Reimbursement
    @reimbursements = policy_scope(Reimbursement)
  end

  def new
    authorize Reimbursement
    @reimbursement = Reimbursement.new(user: current_user)
  end

  def create
    authorize Reimbursement

    reimbursement = Reimbursement.new(reimbursement_params)
    reimbursement.user = current_user

    if reimbursement.save
      flash[:success] = 'Reimbursement requested'
      redirect_to reimbursements_path
    else
      flash[:error] = 'Error creating reimbursement'
      redirect_to new_reimbursement_path
    end
  end

  def destroy
    reimbursement = Reimbursement.find(params[:id])
    authorize reimbursement

    reimbursement.delete
    flash[:success] = 'Reimbursement deleted'
    redirect_to reimbursements_path
  end

  def accept
    reimbursement_service = ReimbursementService.new(params[:reimbursement_id])
    authorize reimbursement_service.reimbursement

    reimbursement_service.accept!

    flash[:success] = 'Reimbursement accepted'
    redirect_to reimbursements_path
  end

  def reject
    reimbursement_service = ReimbursementService.new(params[:reimbursement_id])
    authorize reimbursement_service.reimbursement

    reimbursement_service.reject!

    flash[:success] = 'Reimbursement rejected'
    redirect_to reimbursements_path
  end

  private

  def reimbursement_params
    params.require(:reimbursement).permit(:zkb_link)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    authorize User
    @users = User.all
  end

  def profile
    authorize User

    @user = current_user
    @user_service = UserService.new(@user.token)
  end

  def show
    @user = User.find(params[:id])

    authorize @user
    @user_service = UserService.new(@user.token)
  end

  def welcome_application
    authorize User
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def portrait_url(type, id, size)
    case type.to_sym
    when :character
      "https://imageserver.eveonline.com/Character/#{id}_#{size}.jpg"
    when :corporation
      "https://imageserver.eveonline.com/Corporation/#{id}_#{size}.png"
    when :alliance
      "https://imageserver.eveonline.com/Alliance/#{id}_#{size}.png"
    end
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/helpers/recruiting_mailing_helper.rb
module RecruitingMailingHelper
end

app/helpers/reimbursement_helper.rb
module ReimbursementHelper
  def reimbursement_status_css_class(reimbursement)
    type = case reimbursement.status
           when 'pending'
             'info'
           when 'rejected'
             'danger'
           when 'accepted'
             'success'
           end
    "label label-md label-status label-#{type}"
  end
end

app/helpers/user_helper.rb
module UserHelper
  def money_transaction_css_class(amount)
    type = amount >= 0 ? "positive" : "negative"
    "money-transaction transaction-#{type}"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reimbursements/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Request reimbursement</div>
  <div class="panel-body">
    <%= simple_form_for @reimbursement do |f| %>
      <%= f.input :zkb_link, input_html: { type: 'url', autocomplete: 'off' }, required: true, placeholder: 'Zkillboard link', label: false %>

      <%= f.button :submit, 'Request reimbursement', class: 'btn btn-success pull-right' %>
    <% end %>
  </div>
</div>'

app/views/reimbursements/index.html.erb
<div class="row">
  <%= link_to 'Request Reimbursement', new_reimbursement_path, class: 'btn btn-sm btn-primary action-link' %>
  <table class="table fuschia_table">
    <thead class="thead-dark">
      <tr>
        <th width="5%" scope="col">#</th>
        <th width="30%" scope="col">Name</th>
        <th width="40%" scope="col">Link</th>
        <th width="10%" scope="col">Status</th>
        <th width="20%" scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @reimbursements.each_with_index do |reimbursement, index| %>
        <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td>
          <img width="32" height="32" src="<%= portrait_url(:character, reimbursement.user.character_id, 32) %>">
          <%= reimbursement.user.name %>
        </td>
        <td>
          <%= link_to reimbursement.zkb_link, reimbursement.zkb_link %>
        </td>
          <td>
            <span class="<%= reimbursement_status_css_class(reimbursement) %>"><%= reimbursement.status %></span>
          </td>
        <td>
          <% if policy(reimbursement).destroy? %>
            <%= link_to reimbursement_path(reimbursement), method: :delete do %>
              <span class="btn btn-danger">Delete</span>
            <% end %>
          <% else %>
            <%= link_to reimbursement_accept_path(reimbursement), method: :post do %>
              <span class="btn btn-success">Yes</span>
            <% end %>
            <%= link_to reimbursement_reject_path(reimbursement), method: :post do %>
              <span class="btn btn-danger">No</span>
            <% end %>
          <% end %>
        </td>
        </tr>
        <% end  %>
    </tbody>
  </table>
</div>

app/views/reimbursements/new.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to 'Back', reimbursements_path, class: 'btn btn-sm btn-primary action-link' %>
    <%= render 'form', reimbursement: @reimbursement %>
  </div>
</div>

app/views/user/_contacts_info.html.erb
<div id="user-contacts" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th width="15%" scope="col">Type</th>
      <th width="25%" scope="col">Name</th>
    </tr>
    </thead>
    <tbody>
    <% @user_service.character_contacts.each_with_index do |journal, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td>
          <%= journal[:contact_type].titleize %>
        </td>
        <td>
          <%= journal[:info][:name].titleize %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/user/_employment_info.html.erb
<div id="user-employment" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th class="text-left" width="45%" scope="col">Corporation Name</th>
      <th width="30%" scope="col">Ticker</th>
      <th width="20%" scope="col">Start Date</th>
    </tr>
    </thead>
    <tbody>
    <% @user_service.character_corporation_history.each_with_index do |corporation, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td class="text-left">
          <img src="https://imageserver.eveonline.com/Corporation/<%= corporation[:corporation_id] %>_32.png" style="height: 32px; width: 32px;">
          <%= corporation[:info][:name] %>
        </td>
        <td>
          <%= corporation[:info][:ticker] %>
        </td>
        <td>
          <%= corporation[:start_date].to_date %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/user/_finances_info.html.erb
<div id="user-finances" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th width="15%" scope="col">Date</th>
      <th width="25%" scope="col">Amount</th>
      <th width="25%" scope="col">Type</th>
      <th width="15%" scope="col">Amount</th>
      <th width="15%" scope="col">Balance</th>
    </tr>
    </thead>
    <tbody>
    <% @user_service.character_wallet_journal.each_with_index do |journal, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td>
          <%= journal[:date] %>
        </td>
        <td>
          <%= journal[:ref_type].titleize %>
        </td>
        <td>
          <%= number_with_delimiter(journal[:amount], delimiter: ',') %>
        </td>
        <td>
          <%= number_with_delimiter(journal[:balance], delimiter: ',') %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/user/_mails_info.html.erb
<div id="user-mails" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th class="text-left" width="20%" scope="col">Date</th>
      <th class="text-left" width="70%" scope="col">Subject</th>
      <th width="5%" scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @user_service.character_mails_list.each_with_index do |mail, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td class="text-left">
          <%= mail[:timestamp].to_date %>
        </td>
        <td class="text-left">
          <img src="https://imageserver.eveonline.com/Character/<%= mail[:from] %>_32.jpg" style="height: 32px; width: 32px;">
          <%= mail[:subject] %>
        </td>
        <td class="text-left">
          <%= link_to 'View', mail_path(mail[:mail_id]), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/users/_contacts_info.html.erb
<div id="user-contacts" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="20%" scope="col">#</th>
      <th width="40%" scope="col">Name</th>
      <th width="40%" scope="col">Type</th>
    </tr>
    </thead>
    <tbody>
    <% user_service.character_contacts.each_with_index do |contact, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td class="text-left">
          <img width="32" height="32" src="<%= portrait_url(contact[:contact_type], contact[:contact_id], 32) %>">
          <%= contact[:info][:name].titleize %>
        </td>
        <td>
          <%= contact[:contact_type].titleize %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/users/_employment_info.html.erb
<div id="user-employment" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th class="text-left" width="40%" scope="col">Corporation Name</th>
      <th width="20%" scope="col">Ticker</th>
      <th width="20%" scope="col">Join Date</th>
      <th width="20%" scope="col">Time in Corp</th>
    </tr>
    </thead>
    <tbody>
    <% user_service.character_corporation_history.each_with_index do |corporation, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td class="text-left">
          <img width="32" height="32" src="<%= portrait_url(:corporation, corporation[:corporation_id], 32) %>">
          <%= corporation[:info][:name] %>
        </td>
        <td>
          <%= corporation[:info][:ticker] %>
        </td>
        <td>
          <%= corporation[:start_date].to_date %>
        </td>
        <td>
          <%= corporation[:total_days] %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/users/_finances_info.html.erb
<div id="user-finances" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="15%" scope="col">Date</th>
      <th width="25%" scope="col">Type</th>
      <th width="25%" scope="col">Amount</th>
      <th width="15%" scope="col">Balance</th>
    </tr>
    </thead>
    <tbody>
    <% user_service.character_wallet_journal.each do |journal| %>
      <tr>
        <td>
          <%= journal[:date].to_date %>
        </td>
        <td>
          <%= journal[:ref_type].titleize %>
        </td>
        <td>
          <span class="<%= money_transaction_css_class(journal[:amount]) %>"><%= number_with_delimiter(journal[:amount], delimiter: ',') %><span>
        </td>
        <td>
          <%= number_with_delimiter(journal[:balance], delimiter: ',') %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/users/_general_info.html.erb
<div id="user-general" class="user-general-container">
  <div class="row">
    <div class="col-md-6">
      <div class="col-md-5">
        <img width="200" height="200" src="<%= portrait_url(:character, user.character_id, 200) %>">
      </div>
      <div class="col-md-7">
        <h4><%= user.name %></h4>
        <span>
          <img width="16" height="16" src="<%= portrait_url(:corporation, user.corporation_id, 32) %>">
          <%= user_service.corporation_info[:name]%>
        </span>
        <span>
          <img width="16" height="16" src="<%= portrait_url(:alliance, user.alliance_id, 32) %>">
          <%= user_service.alliance_info[:name]%>
        </span>
      </div>
    </div>
    <div class="col-md-3">
      <h4>Clone</h4>
      <span>Sec Status: <%= user_service.character_info[:security_status].round(1)%></span>
      <span>Total SP: <%=  number_with_delimiter(user_service.character_skills[:total_sp], delimiter: ',') %></span>
      <span>Wallet: <%=  number_with_delimiter(user_service.character_wallet.to_f.round(0), delimiter: ',') %> ISK</span>
    </div>
    <div class="col-md-3">
      <h4>Account</h4>
      <span>Birthday: <%= user_service.character_info[:birthday].to_date %> (<%= Date.today.mjd - user_service.character_info[:birthday].to_date.mjd %>) days </span>
    </div>
  </div>
</div>

app/views/users/_mails_info.html.erb
<div id="user-mails" class="hidden">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th class="text-left" width="20%" scope="col">Date</th>
      <th class="text-left" width="70%" scope="col">Subject</th>
      <th width="5%" scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% user_service.character_mails_list.each_with_index do |mail, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td class="text-left">
          <%= mail[:timestamp].to_date %>
        </td>
        <td class="text-left">
          <img width="32" height="32" src="<%= portrait_url(:character, mail[:from], 32) %>">
          <%= mail[:subject] %>
        </td>
        <td class="text-left">
          <%= link_to 'View', mail_path(mail[:mail_id]), class: 'btn btn-primary', target: :_blank %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/users/application.html.erb
<div class="container">
  <div class="row">
    <div class="welcome-container text-center">
      <h2 class="col-sm-12">Thanks for applying to Fuschia Fleet, we are processing your application.</h2>
      <h2 class="col-sm-12">We will contact you when the process is completed.</h2>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <table class="table fuschia_table">
    <thead class="thead-dark">
    <tr>
      <th width="5%" scope="col">#</th>
      <th class="text-left" width="75%" scope="col">Name</th>
      <th width="20%" scope="col">Action</th>
    </tr>
    </thead>
    <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td class="text-left" >
          <img width="32" height="32" src="<%= portrait_url(:character, user.character_id, 32) %>">
          <%= user.name %>
        </td>
        <td>
          <%= link_to 'View', user, class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end  %>
    </tbody>
  </table>
</div>

app/views/users/profile.html.erb
<div id="profile-nabvar" class="container navbar navbar-inverse navbar-fixed-left profile-nabvar">
  <ul class="nav navbar-nav">
    <li><a href="#user-general">General</a></li>
    <li><a href="#user-finances">Finance</a></li>
    <li><a href="#user-employment">Employment</a></li>
    <li><a href="#user-contacts">Contacts</a></li>
    <li><a href="#user-mails">Mails</a></li>
  </ul>
</div>

<div id="user-profile" class="user-profile-container panel-container container">
  <%= render 'general_info', user: @user, user_service: @user_service %>
  <%= render 'finances_info', user_service: @user_service %>
  <%= render 'employment_info', user_service: @user_service %>
  <%= render 'contacts_info', user_service: @user_service %>
  <%= render 'mails_info', user_service: @user_service %>
</div>

app/views/users/show.html.erb
<div id="profile-nabvar" class="container navbar navbar-inverse navbar-fixed-left profile-nabvar">
  <ul class="nav navbar-nav">
    <li><a href="#user-general">General</a></li>
    <li><a href="#user-finances">Finance</a></li>
    <li><a href="#user-employment">Employment</a></li>
    <li><a href="#user-contacts">Contacts</a></li>
    <li><a href="#user-mails">Mails</a></li>
  </ul>
</div>

<div id="user-profile" class="user-profile-container panel-container container">
  <%= render 'general_info', user: @user, user_service: @user_service %>
  <%= render 'finances_info', user_service: @user_service %>
  <%= render 'employment_info', user_service: @user_service %>
  <%= render 'contacts_info', user_service: @user_service %>
  <%= render 'mails_info', user_service: @user_service %>
</div>

app/views/users/welcome_application.html.erb
<div class="container">
  <div class="row">
    <div class="welcome-container text-center">
      <h2 class="col-sm-12">Thanks for applying to Fuschia Fleet, we are processing your application.</h2>
      <h2 class="col-sm-12">We will contact you when the process is completed.</h2>
    </div>
  </div>
</div>