config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :auth do
    post 'cpplogin', to: 'authentication#login'
    post 'logout', to: 'authentication#logout'
    get 'callback', to: 'authentication#callback'
  end

  namespace :recruit do
    get 'mailing/add', to: 'recruiting_mailing#new'
    post 'mailing/add', to: 'recruiting_mailing#create'
  end

  resources :reimbursements do
    post :accept
    post :reject
  end

  resources :users do
    collection do
      get 'profile'
      get 'welcome_application'

      resources :mails
    end
  end

  resources :applications, as: :application do
    post :accept
    post :reject
  end
end

app/models/application.rb
class Application < ApplicationRecord
  include AASM

  default_scope { order(created_at: :desc) }

  validates :character_id, presence: true
  validates :token, presence: true
  validates :name, presence: true
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  aasm column: 'status' do
    state :pending, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: [:pending], to: :accepted
    end

    event :reject do
      transitions from: [:pending], to: :rejected
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
end

app/models/eve_mail.rb
class EveMail
end

app/models/recruiting_mailing.rb
class RecruitingMailing < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/reimbursement.rb
class Reimbursement < ApplicationRecord
  include AASM

  belongs_to :user

  default_scope { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :zkb_link, presence: true, uniqueness: true
  validates :status, presence: true, inclusion: { in: %w(pending accepted rejected) }

  aasm column: 'status' do
    state :pending, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: [:pending, :accepted,:rejected], to: :accepted
    end

    event :reject do
      transitions from: [:pending, :accepted,:rejected], to: :rejected
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  include AccountSetup

  has_many :roles, dependent: :destroy
  has_many :reimbursements, dependent: :destroy

  validates :user_id, presence: true, uniqueness: true
  validates :name, presence: true
  validates :character_id, presence: true, uniqueness: true
  validates :corporation_id, presence: true
  validates :alliance_id, presence: true
  validates :token, presence: true
end

app/controllers/mail_controller.rb
class MailController < ApplicationController
  def show
    authorize EveMail

    @mail = UserService.new(current_user.token).character_mail(params[:id])
  end
end

app/controllers/mails_controller.rb
class MailsController < ApplicationController
  def show
    authorize EveMail

    @mail = UserService.new(current_user.token).character_mail(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    authorize User
    @users = User.all
  end

  def profile
    authorize User

    @user = current_user
    @user_service = UserService.new(@user.token)
  end

  def show
    @user = User.find(params[:id])

    authorize @user
    @user_service = UserService.new(@user.token)
  end

  def welcome_application
    authorize User
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def portrait_url(type, id, size)
    case type.to_sym
    when :character
      "https://imageserver.eveonline.com/Character/#{id}_#{size}.jpg"
    when :corporation
      "https://imageserver.eveonline.com/Corporation/#{id}_#{size}.png"
    when :alliance
      "https://imageserver.eveonline.com/Alliance/#{id}_#{size}.png"
    end
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/mail_helper.rb
module MailHelper
end

app/helpers/recruiting_mailing_helper.rb
module RecruitingMailingHelper
end

app/helpers/reimbursement_helper.rb
module ReimbursementHelper
  def reimbursement_status_css_class(reimbursement)
    type = case reimbursement.status
           when 'pending'
             'info'
           when 'rejected'
             'danger'
           when 'accepted'
             'success'
           end
    "label label-md label-status label-#{type}"
  end
end

app/helpers/user_helper.rb
module UserHelper
  def money_transaction_css_class(amount)
    type = amount >= 0 ? "positive" : "negative"
    "money-transaction transaction-#{type}"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <title>Fuschia Fleet Service</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <div class="bear-drinking-container">
            <%= image_tag('bear-drinking.png', alt: 'Bear Drinking') %>
          </div>
          Fuschia Fleet
        </a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <% if is_authenticated? %>
          <li><%= link_to "Reimbursements", reimbursements_path %></li>
        <% end %>
        <% if is_authenticated? && policy(RecruitingMailing).new? %>
          <li><%= link_to "Recruiting Mailing", recruit_mailing_add_path %></li>
        <% end %>
        <% if is_authenticated? && policy(Application).index? %>
          <li><%= link_to "Applications", application_index_path %></li>
        <% end %>
        <% if is_authenticated? && policy(User).index? %>
          <li><%= link_to "Users", users_path %></li>
        <% end %>
      </ul>
      <% unless is_authenticated? %>
        <%= simple_form_for :cpp_login, url: auth_cpplogin_path do |f| %>
          <%= f.button :submit, '', class: 'cpplogin-btn' %>
        <% end %>
      <% else %>
        <div class="user-menu-container">
          <div class="col-sm-7">
            <%= link_to profile_users_path, class: 'current-user-name' do %>
              <span class="current-user-name"><%= current_user.name %></span>
            <% end %>
          </div>
          <div class="col-sm-5">
            <%= simple_form_for :logout, url: auth_logout_path do |f| %>
              <%= f.button :submit, 'Logout', class: 'btn btn-primary logout-btn' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</header>

<%= render 'shared/flash_messages' %>

<div class="container master-container">
  <%= yield %>
</div>

<footer class="footer">
  <div class="container">
    <div class="pull-left span-3" style="text-align:left">
      <p>
        EVE Online and the EVE logo are the registered trademarks of CCP hf. All rights are reserved worldwide.
        All other trademarks are the property of their respective owners. EVE Online, the EVE logo, EVE and all associated
        logos and designs are the intellectual property of CCP hf. All artwork, screenshots, characters, vehicles, storylines,
        world facts or other recognizable features of the intellectual property relating to these trademarks are likewise the
        intellectual property of CCP hf. CCP is in no way responsible for the content on or functioning of this website, nor
        can it be liable for any damage arising from the use of this website.
      </p>
      <br>
      <p>
        All EVE related materials are property of <a href="http://www.ccpgames.com">CCP Games</a><br>
      </p>
    </div>
  </div>
</footer>
</body>
</html>

app/views/shared/_flash_messages.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>